// Code generated by "stringer -type=Command"; DO NOT EDIT.

package u2ftoken

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Register-1]
	_ = x[Authenticate-2]
	_ = x[Version-3]
}

const _Command_name = "RegisterAuthenticateVersion"

var _Command_index = [...]uint8{0, 8, 20, 27}

func (i Command) String() string {
	i -= 1
	if i >= Command(len(_Command_index)-1) {
		return "Command(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Command_name[_Command_index[i]:_Command_index[i+1]]
}
