// Code generated by "stringer -type=command"; DO NOT EDIT.

package u2ftoken

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Register-1]
	_ = x[Authenticate-2]
	_ = x[Version-3]
}

const _command_name = "RegisterAuthenticateVersion"

var _command_index = [...]uint8{0, 8, 20, 27}

func (i command) String() string {
	i -= 1
	if i >= command(len(_command_index)-1) {
		return "command(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _command_name[_command_index[i]:_command_index[i+1]]
}
