// Code generated by "stringer -type=errorCode"; DO NOT EDIT.

package u2ftoken

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[noError-36864]
	_ = x[errConditionNotSatisfied-27013]
	_ = x[errWrongData-27264]
	_ = x[errWrongLength-26368]
	_ = x[errClaNotSupported-28160]
	_ = x[errInsNotSupported-27904]
}

const (
	_errorCode_name_0 = "ErrWrongLength"
	_errorCode_name_1 = "ErrConditionNotSatisfied"
	_errorCode_name_2 = "ErrWrongData"
	_errorCode_name_3 = "ErrInsNotSupported"
	_errorCode_name_4 = "ErrClaNotSupported"
	_errorCode_name_5 = "NoError"
)

func (i errorCode) String() string {
	switch {
	case i == 26368:
		return _errorCode_name_0
	case i == 27013:
		return _errorCode_name_1
	case i == 27264:
		return _errorCode_name_2
	case i == 27904:
		return _errorCode_name_3
	case i == 28160:
		return _errorCode_name_4
	case i == 36864:
		return _errorCode_name_5
	default:
		return "errorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
