// Code generated by "stringer -type=u2fError"; DO NOT EDIT.

package u2fhid

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[none-0]
	_ = x[invalidCmd-1]
	_ = x[invalidPar-2]
	_ = x[invalidLen-3]
	_ = x[invalidSeq-4]
	_ = x[msgTimeout-5]
	_ = x[channelBusy-6]
	_ = x[lockRequired-10]
	_ = x[invalidCid-11]
	_ = x[other-127]
}

const (
	_u2fError_name_0 = "noneinvalidCmdinvalidParinvalidLeninvalidSeqmsgTimeoutchannelBusy"
	_u2fError_name_1 = "lockRequiredinvalidCid"
	_u2fError_name_2 = "other"
)

var (
	_u2fError_index_0 = [...]uint8{0, 4, 14, 24, 34, 44, 54, 65}
	_u2fError_index_1 = [...]uint8{0, 12, 22}
)

func (i u2fError) String() string {
	switch {
	case i <= 6:
		return _u2fError_name_0[_u2fError_index_0[i]:_u2fError_index_0[i+1]]
	case 10 <= i && i <= 11:
		i -= 10
		return _u2fError_name_1[_u2fError_index_1[i]:_u2fError_index_1[i+1]]
	case i == 127:
		return _u2fError_name_2
	default:
		return "u2fError(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
