// Code generated by "stringer -type=u2fError"; DO NOT EDIT.

package u2fhid

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[InvalidCmd-1]
	_ = x[InvalidPar-2]
	_ = x[InvalidLen-3]
	_ = x[InvalidSeq-4]
	_ = x[MsgTimeout-5]
	_ = x[ChannelBusy-6]
	_ = x[LockRequired-10]
	_ = x[InvalidCid-11]
	_ = x[Other-127]
}

const (
	_u2fError_name_0 = "NoneInvalidCmdInvalidParInvalidLenInvalidSeqMsgTimeoutChannelBusy"
	_u2fError_name_1 = "LockRequiredInvalidCid"
	_u2fError_name_2 = "Other"
)

var (
	_u2fError_index_0 = [...]uint8{0, 4, 14, 24, 34, 44, 54, 65}
	_u2fError_index_1 = [...]uint8{0, 12, 22}
)

func (i u2fError) String() string {
	switch {
	case i <= 6:
		return _u2fError_name_0[_u2fError_index_0[i]:_u2fError_index_0[i+1]]
	case 10 <= i && i <= 11:
		i -= 10
		return _u2fError_name_1[_u2fError_index_1[i]:_u2fError_index_1[i+1]]
	case i == 127:
		return _u2fError_name_2
	default:
		return "u2fError(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
